after_success:
- coveralls -e _travis/install -e tests
- git config --global user.name "Travis CI"
- git config --global user.email "thomas.moulard+travis@gmail.com"
- git remote set-url origin https://thomas-moulard:${GH_TOKEN}@github.com/stack-of-tasks/sot-dynamic.git
- git fetch origin gh-pages:gh-pages
- cd _travis/build/doc && ../../../cmake/github/update-doxygen-doc.sh
branches:
  only:
  - disabled_travis_because_not_relevant_anymore
compiler:
- clang
- gcc
matrix:
  allow_failures:
  - compiler: clang

before_install:
- git submodule update --init --recursive
#Add robotpkg and pinocchio dependencies
- sudo sh -c "echo \"deb http://robotpkg.openrobots.org/packages/debian/pub precise robotpkg\" >> /etc/apt/sources.list "
- curl http://robotpkg.openrobots.org/packages/debian/robotpkg.key | sudo apt-key add -
- sudo apt-get update -qq
- sudo apt-get install -qq doxygen doxygen-latex libboost-all-dev libeigen3-dev liblapack-dev libblas-dev gfortran python-dev
  python-sphinx python-numpy libtinyxml-dev robotpkg-console-bridge robotpkg-urdfdom-headers robotpkg-urdfdom robotpkg-eigenpy
- sudo pip install cpp-coveralls
language: cpp
notifications:
  email:
  - hpp-source@laas.fr
script: ./.travis/build
env:
  global:
    secure: dXnBor2MQ2eUyh6WqB6FKWWcE3MxzY8fin7xTyA+yJwpUsEgkvXp/4IEzx4CDSIjrLSR4P/MKQby9jnd+vTDOMH1NwXkdQH8c7mn/L3ZshALMKVNZIW6IDNx7jneAMud4/l9KHvauQVdby4cA7gFxbVQi+aPbhnioN4UO0AeLeA=
